spring:
  config:
    activate:
      on-profile: prod
  output:
    ansi:
      enabled: never
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

server:
  shutdown: graceful

logging:
  file:
    name: ${LOG_FILE_PATH:logs/application.log}
