package live.lbtrip.global.error;

import org.springframework.http.HttpStatus;

import lombok.Getter;

@Getter
public enum ErrorCode {

    INVALID_INPUT_VALUE(HttpStatus.BAD_REQUEST),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    DUPLICATE_EMAIL(HttpStatus.CONFLICT),
    PASSWORD_CONFIRM_MISMATCH(HttpStatus.BAD_REQUEST),
    REQUIRED_AGREEMENT_NOT_ACCEPTED(HttpStatus.BAD_REQUEST),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    EMAIL_ALREADY_VERIFIED(HttpStatus.CONFLICT),
    EMAIL_VERIFICATION_CODE_NOT_FOUND(HttpStatus.NOT_FOUND),
    EMAIL_VERIFICATION_CODE_EXPIRED(HttpStatus.BAD_REQUEST),
    EMAIL_VERIFICATION_CODE_USED(HttpStatus.BAD_REQUEST),
    PASSWORD_RESET_CODE_NOT_FOUND(HttpStatus.NOT_FOUND),
    PASSWORD_RESET_CODE_EXPIRED(HttpStatus.BAD_REQUEST),
    PASSWORD_RESET_CODE_USED(HttpStatus.BAD_REQUEST),
    PASSWORD_RESET_TOKEN_NOT_FOUND(HttpStatus.NOT_FOUND),
    PASSWORD_RESET_TOKEN_EXPIRED(HttpStatus.BAD_REQUEST),
    PASSWORD_RESET_TOKEN_USED(HttpStatus.BAD_REQUEST),
    EMAIL_SEND_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_LOGIN_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    EMAIL_NOT_VERIFIED(HttpStatus.FORBIDDEN),
    USER_WITHDRAWN(HttpStatus.FORBIDDEN),
    INVALID_ACCESS_TOKEN(HttpStatus.UNAUTHORIZED),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
    EXPIRED_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
    PROPENSITY_NOT_FOUND(HttpStatus.NOT_FOUND),
    TRAVEL_PROFILE_NOT_FOUND(HttpStatus.INTERNAL_SERVER_ERROR),
    REGION_NOT_FOUND(HttpStatus.NOT_FOUND),
    COURSE_NOT_FOUND(HttpStatus.NOT_FOUND),
    SAVED_COURSE_NOT_FOUND(HttpStatus.NOT_FOUND),
    TOUR_API_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    TOUR_API_QUOTA_EXCEEDED(HttpStatus.SERVICE_UNAVAILABLE),
    TOUR_DATA_NOT_READY(HttpStatus.SERVICE_UNAVAILABLE),
    TOUR_SYNC_IN_PROGRESS(HttpStatus.CONFLICT),
    INVALID_ADMIN_ACCESS_TOKEN(HttpStatus.UNAUTHORIZED),
    INCENTIVE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INCENTIVE_REGION_INVALID(HttpStatus.BAD_REQUEST),
    INVALID_INCENTIVE_PERIOD(HttpStatus.BAD_REQUEST),
    RECOMMENDATION_GENERATION_FAILED(HttpStatus.SERVICE_UNAVAILABLE),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    DUPLICATE_SAVE_COURSE(HttpStatus.CONFLICT),
    SAVED_COURSE_PLACE_NOT_FOUND(HttpStatus.NOT_FOUND),
    TOUR_ALREADY_COMPLETED(HttpStatus.CONFLICT),
    TOUR_NOT_IN_PROGRESS(HttpStatus.CONFLICT),
    INVALID_IMAGE_TYPE(HttpStatus.BAD_REQUEST),
    IMAGE_SIZE_EXCEEDED(HttpStatus.CONTENT_TOO_LARGE),
    IMAGE_UPLOAD_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    IMAGE_NOT_FOUND(HttpStatus.NOT_FOUND),
    IMAGE_ALREADY_ATTACHED(HttpStatus.CONFLICT),
    TOUR_RECEIPT_NOT_FOUND(HttpStatus.NOT_FOUND),
    TOUR_REPORT_NOT_AVAILABLE(HttpStatus.CONFLICT),
    TERMS_NOT_FOUND(HttpStatus.NOT_FOUND),
    SHARE_TOKEN_NOT_FOUND(HttpStatus.NOT_FOUND),
    SHARE_TOKEN_EXPIRED(HttpStatus.GONE),
    ;

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }
}
